### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [ealdent/uea-stemmer#4]
Dear Jason,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. 

Thank you for the project!

**Comment by ealdent** [comment]
Done!  Thanks for bringing this to my attention.

**Comment by arbox** [comment]
You're welcome! Use the list, make it useful for others! Thank you for your project and contributions!
